"""Core domain models for the Vetra control plane."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field

from vetra.core.enums import (
    CacheLocation,
    DecisionType,
    EngineType,
    FeatureStatus,
    ModalityType,
    QuantizationPrecision,
    SecurityAction,
)


def utc_now() -> datetime:
    """Return current UTC datetime."""
    return datetime.now(timezone.utc)


class KVBlockStats(BaseModel):
    """Metadata and access statistics for a logical KV cache block."""

    model_config = ConfigDict(extra="ignore")

    block_id: str = Field(..., description="Unique identifier for the KV block")
    tenant_id: str = Field(default="default", description="Tenant owning this cache block")
    session_id: Optional[str] = Field(default=None, description="Conversation or session ID")
    request_id: Optional[str] = Field(default=None, description="Latest request utilizing this block")
    token_count: int = Field(default=16, ge=1, description="Number of tokens stored in this block")
    created_at: datetime = Field(default_factory=utc_now)
    last_accessed_at: datetime = Field(default_factory=utc_now)
    access_count: int = Field(default=1, ge=0, description="Total times this block was referenced")
    reuse_count: int = Field(default=0, ge=0, description="Times this block was reused across requests")
    hit_count: int = Field(default=1, ge=0, description="Cache hits on this block")
    miss_count: int = Field(default=0, ge=0, description="Cache misses requiring regeneration")
    gpu_memory_bytes: int = Field(default=0, ge=0, description="GPU memory occupied by this block")
    cpu_memory_bytes: int = Field(default=0, ge=0, description="CPU memory occupied if offloaded")
    location: CacheLocation = Field(default=CacheLocation.GPU, description="Current physical location")
    importance_score: float = Field(default=0.5, ge=0.0, le=1.0, description="Normalized importance [0, 1]")
    ttl_seconds: Optional[int] = Field(default=None, description="Time to live in seconds")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Custom metadata tags")


class GPUStats(BaseModel):
    """Real-time GPU memory and computation statistics."""

    model_config = ConfigDict(extra="ignore")

    total_memory_bytes: int = Field(default=0, ge=0)
    used_memory_bytes: int = Field(default=0, ge=0)
    free_memory_bytes: int = Field(default=0, ge=0)
    utilization_percent: float = Field(default=0.0, ge=0.0, le=100.0)
    kv_memory_bytes: int = Field(default=0, ge=0)
    kv_utilization_percent: float = Field(default=0.0, ge=0.0, le=100.0)
    gpu_temperature_celsius: Optional[float] = None
    device_name: str = Field(default="Unknown GPU")
    timestamp: datetime = Field(default_factory=utc_now)

    @property
    def memory_pressure(self) -> float:
        """Fraction of GPU memory currently allocated [0.0, 1.0]."""
        if self.total_memory_bytes <= 0:
            return 0.0
        return min(1.0, self.used_memory_bytes / self.total_memory_bytes)


class RequestStats(BaseModel):
    """Request-level inference and cache utilization metrics."""

    model_config = ConfigDict(extra="ignore")

    request_id: str
    tenant_id: str = "default"
    session_id: Optional[str] = None
    prompt_tokens: int = Field(default=0, ge=0)
    cached_tokens: int = Field(default=0, ge=0)
    computed_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    ttft_ms: Optional[float] = Field(default=None, description="Time to First Token in milliseconds")
    total_latency_ms: Optional[float] = Field(default=None, description="End-to-end latency in ms")
    cache_hit: bool = Field(default=False)
    hit_rate: float = Field(default=0.0, ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=utc_now)


class CacheEvent(BaseModel):
    """Audit and telemetry event for cache state transitions."""

    model_config = ConfigDict(extra="ignore")

    event_id: Optional[str] = None
    timestamp: datetime = Field(default_factory=utc_now)
    event_type: str = Field(..., description="e.g., hit, miss, allocate, offload, evict, prefetch")
    block_id: str
    request_id: Optional[str] = None
    tenant_id: str = "default"
    tokens: int = 16
    location: CacheLocation = CacheLocation.GPU
    latency_ms: Optional[float] = None
    details: Dict[str, Any] = Field(default_factory=dict)


class Recommendation(BaseModel):
    """Action recommendation generated by the Vetra policy engine."""

    model_config = ConfigDict(extra="ignore")

    block_id: str
    tenant_id: str = "default"
    decision: DecisionType
    score: float = Field(default=0.5, ge=0.0, le=1.0)
    reason: str
    expected_memory_saving_bytes: int = 0
    expected_latency_delta_ms: float = 0.0
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    created_at: datetime = Field(default_factory=utc_now)


class PolicyConstraints(BaseModel):
    """Configurable constraints governing policy evaluation."""

    max_gpu_memory_percent: float = Field(default=0.85, ge=0.1, le=1.0)
    min_cache_hit_rate: float = Field(default=0.40, ge=0.0, le=1.0)
    max_ttft_ms: Optional[float] = Field(default=500.0)
    max_cpu_memory_percent: float = Field(default=0.80, ge=0.1, le=1.0)
    max_offload_bandwidth_mbps: Optional[float] = Field(default=10000.0)
    max_cost_per_hour_usd: Optional[float] = None
    tenant_priority: int = Field(default=1, ge=1, le=10)
    minimum_block_importance: float = Field(default=0.20, ge=0.0, le=1.0)


class EngineCapabilities(BaseModel):
    """Hardware and engine capability discovery contract."""

    engine_type: EngineType = EngineType.VLLM
    version: str = "unknown"
    telemetry: bool = True
    request_metrics: bool = True
    block_metadata: bool = True
    direct_kv_control: bool = False
    offload: bool = False
    prefetch: bool = False
    eviction: bool = False
    quantization: bool = False
    remote_kv: bool = False
    semantic_reuse: bool = False
    status: FeatureStatus = FeatureStatus.IMPLEMENTED
    notes: Optional[str] = None


class UnifiedDecision(BaseModel):
    """Central unified contract connecting Intelligence, Security, Economics, and Execution."""

    model_config = ConfigDict(extra="ignore")

    block_id: str
    tenant_id: str = "default"
    current_location: CacheLocation = CacheLocation.GPU
    recommended_location: CacheLocation = CacheLocation.GPU
    decision: DecisionType = DecisionType.KEEP
    importance: float = Field(default=0.5, ge=0.0, le=1.0)
    reuse_probability: float = Field(default=0.5, ge=0.0, le=1.0)
    gpu_pressure: float = Field(default=0.0, ge=0.0, le=1.0)
    cpu_pressure: float = Field(default=0.0, ge=0.0, le=1.0)
    expected_memory_saving_bytes: int = 0
    expected_latency_delta_ms: float = 0.0
    expected_cost_delta_usd: float = 0.0
    security_decision: SecurityAction = SecurityAction.ALLOW
    security_reason: Optional[str] = None
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    reason: str = "Default policy evaluation"
    policy_version: str = "v1.0"
    timestamp: datetime = Field(default_factory=utc_now)


class CacheObject(BaseModel):
    """Multimodal cache unit abstraction for future text, image, audio, video KV tensors."""

    object_id: str
    modality: ModalityType = ModalityType.TEXT
    shape: List[int] = Field(default_factory=list)
    dtype: str = "float16"
    size_bytes: int = 0
    owner_tenant_id: str = "default"
    location: CacheLocation = CacheLocation.GPU
    created_at: datetime = Field(default_factory=utc_now)
    lifecycle_state: str = "active"


class Prediction(BaseModel):
    """Predictive ML / heuristic inference forecast."""

    reuse_probability: float = Field(default=0.5, ge=0.0, le=1.0)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    horizon_seconds: float = Field(default=60.0, gt=0.0)
    model_type: str = "heuristic"
    features_used: List[str] = Field(default_factory=list)


class PlacementDecision(BaseModel):
    """Placement recommendation for physical storage tiers."""

    block_id: str
    target_location: CacheLocation
    score: float = 0.5
    estimated_transfer_time_ms: float = 0.0
    reason: str = "Standard placement policy"


class Tenant(BaseModel):
    """Tenant identity definition for multi-tenant isolation."""

    tenant_id: str
    name: str
    priority: int = 1
    max_kv_memory_bytes: Optional[int] = None
    namespaces: List[str] = Field(default_factory=lambda: ["default"])
    created_at: datetime = Field(default_factory=utc_now)


class TenantPolicy(BaseModel):
    """Tenant-specific cache and security governance."""

    tenant_id: str
    allow_cross_tenant_reuse: bool = False
    allowed_namespaces: List[str] = Field(default_factory=lambda: ["default"])
    max_ttl_seconds: int = 3600
    require_encryption: bool = False


class CacheNamespace(BaseModel):
    """Namespace boundary for cache isolation."""

    namespace_id: str
    tenant_id: str
    description: str = ""
    is_public: bool = False


class ACLRule(BaseModel):
    """Access Control List rule for KV cache access."""

    rule_id: str
    source_tenant_id: str
    target_tenant_id: str
    target_namespace: str
    action: SecurityAction = SecurityAction.DENY
    reason: str = "Default tenant isolation"


class SecurityEvent(BaseModel):
    """Security audit record for authorization checks."""

    event_id: str
    timestamp: datetime = Field(default_factory=utc_now)
    source_tenant_id: str
    target_block_id: str
    action_attempted: str
    decision: SecurityAction
    reason: str


class AuditEvent(BaseModel):
    """Traceable decision record for audit and compliance."""

    event_id: str
    timestamp: datetime = Field(default_factory=utc_now)
    actor: str = "policy_engine"
    tenant: str = "default"
    block_id: str
    action: str
    reason: str
    policy_version: str = "v1.0"
    result: str = "SUCCESS"


class CostBreakdown(BaseModel):
    """Detailed economic cost model estimate."""

    estimated_cost_per_hour: float = 0.0
    estimated_cost_per_1m_tokens: float = 0.0
    estimated_gpu_memory_cost: float = 0.0
    estimated_cpu_memory_cost: float = 0.0
    estimated_savings_per_hour: float = 0.0
    is_simulated: bool = True
    currency: str = "USD"
